version: "3.8"

services:
  api:
    build: ./api
    volumes:
      - ./api:/src
    ports:
      - "5001:5000"
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./api/db:/root/db/